version: "3.7"

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    volumes:
      - static:/static
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
volumes:
  static:
