# Generated by Django 4.1.7 on 2023-03-19 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='code', max_length=15)),
                ('amount', models.FloatField(db_column='amount')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('price', models.FloatField(db_column='price')),
                ('discount_price', models.FloatField(blank=True, db_column='discount_price', null=True)),
                ('available_number', models.PositiveIntegerField(db_column='available_number')),
                ('total_number', models.PositiveIntegerField(db_column='total_number')),
                ('description', models.TextField(db_column='description')),
                ('picture', models.ImageField(blank=True, db_column='picture', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=30, unique=True)),
                ('subcategory', models.CharField(blank=True, db_column='subcategory', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, db_column='start_date')),
                ('ordered_date', models.DateTimeField(db_column='ordered_date')),
                ('being_delivered', models.BooleanField(db_column='delivered_status', default=False)),
                ('received', models.BooleanField(db_column='received', default=False)),
                ('refund_requested', models.BooleanField(db_column='refund_requested', default=False)),
                ('refund_granted', models.BooleanField(db_column='refund_granted', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_column='country', default='Romania', max_length=25)),
                ('state', models.CharField(db_column='state', max_length=25)),
                ('city', models.CharField(db_column='city', max_length=25)),
                ('street', models.CharField(db_column='street', max_length=25)),
                ('apartment', models.CharField(blank=True, db_column='apartment', max_length=25, null=True)),
                ('zip_code', models.CharField(db_column='zip_code', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(db_column='street')),
                ('city', models.CharField(db_column='city', max_length=25)),
                ('state', models.CharField(db_column='state', max_length=25)),
                ('country', models.CharField(db_column='country', default='Romania', max_length=25)),
                ('zip_code', models.CharField(db_column='zip_code', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, db_column='profile_picture', null=True, upload_to='')),
                ('date_of_birth', models.DateField(db_column='date_of_birth')),
                ('phone', models.CharField(db_column='phone_number', max_length=10)),
                ('country_code', models.CharField(db_column='country_code', default='+40', max_length=5)),
                ('created_at', models.DateTimeField(auto_now=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first_name', max_length=20)),
                ('last_name', models.CharField(db_column='last_name', max_length=20)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('username', models.CharField(db_column='username', db_index=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('address', models.OneToOneField(blank=True, db_column='address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.useraddress')),
                ('profile', models.OneToOneField(blank=True, db_column='profile', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(db_column='reason')),
                ('accepted', models.BooleanField(db_column='status', default=False)),
                ('order', models.OneToOneField(blank=True, db_column='order', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('order', models.OneToOneField(db_column='order', on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(db_column='quantity', default=1)),
                ('item', models.ForeignKey(blank=True, db_column='item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.item')),
                ('order', models.ForeignKey(db_column='order', on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, db_column='billing_address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='api.orderaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, db_column='coupon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, db_column='shipping_address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='api.orderaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='api.itemcategory'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(db_column='quantity', default=1)),
                ('cart', models.ForeignKey(db_column='cart', on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
                ('item', models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
