# Generated by Django 4.2 on 2023-04-16 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(db_column='cart', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.CASCADE, related_name='item_carts', to='api.item'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(db_column='name', db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='api.item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_column='order', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.order'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('name', 'subcategory')},
        ),
    ]
